### ISSUE TITLE
Unplayable on high resolution monitors

### ISSUE THREAD

**Issue by kossilar** [giann/settlers-issues#1]
The game window and interface are so small that on high resolution monitors the game can't be played comfortably.

**Comment by giann** [comment]
You can configure some aspects of the game in a file named `.settlersrc`. The file must be present in the save directory of the game:
* On Windows: `C:\Users\user\AppData\Roaming\LOVE\settlers\`
* On macOS: `/Users/user/Library/Application Support/LOVE/settlesrs/`
* On Linux: `~/.local/share/love/settlers/`

This is not yet documented but you can actually change the font by writing this in your `.settlersrc`:
```lua
return {
    font = {
        spriteSheet = "assets/fonts/rcurses.png"
    }
}
```

Possible fonts are:
* `buddy.png`
* `cheepicus.png`
* `hallow.png`
* `rcurses.png`
* `redjack.png`
* `sm.png`

See `README.md` that you must have had with the game for other possibles settings. In the future all this will be configurable via the game UI.

**Updated**: Example was incorrect (missing `spriteSheet`)

**Comment by giann** [comment]
Menu to change font available in version [0.0.2b](https://giann.itch.io/settlers-of-the-deep/devlog/59031/002a-released)

**Comment by kossilar** [comment]
Hello. Good job with the font change menu. The game is definitely playable now. I've encountered a few more bugs, but until they recur it will be difficult to nail them down for you. This came could be a hit. I hope you keep working on it.

**Comment by giann** [comment]
Thanks. Don’t hesitate to post an issue even with not much context.
