### ISSUE TITLE
FEEDBACK (not really XD)

### ISSUE THREAD

**Issue by Malmik** [giann/settlers-issues#11]
HI OMG. It happened. Someone mixed my three favourite genres:
Strategy, roguelike and ASCII indie game. Emotional high, led me to this github. You, sir are my guru and I am also love2d dev. Can I have your Discord? becouse I would like to hear your advice on one thing.

**Comment by giann** [comment]
Hey. Glad you liked it! I don't use discord but you can message me on twitter @giann I'm also around on the irc channel of love2d.
