### ISSUE TITLE
Settlers seem to not be eating / Slowing the game down a bit

### ISSUE THREAD

**Issue by Etherum1914** [giann/settlers-issues#14]
The settlers in my games don't seem to be eating. I've been hoarding so much food. I don't know if their diets has been worked on but if it's a possibility, I would hope to see them eat some day.

I also would like to see a setting to allow one to slow or speed up the game itself. It's really hard to see what's happening with how fast the game moves, though it's not  a major issue.

**Comment by giann** [comment]
Peasants don't eat. The food is for miners. Each type of miners needs a different kind of food.

You can speed up the game by hitting `]` and slowing it back down with `[`. You can't slow it down under the normal speed though. This could be done in future versions.
