### ISSUE TITLE
Console registers every key twice

### ISSUE THREAD

**Issue by s-ol** [giann/settlers-issues#4]
After changing the font, then starting a new game and opening the console each key is registered twice (e.g. pressing 's' will print 'ss' in the console).

**Comment by giann** [comment]
Do you mean the in-game debug console ? You should not have access to it on release version my bad.

**Comment by s-ol** [comment]
@giann okay :P but the bug you might want to fix anyway, it seems the keyboard handler is installed 'over' another one and when the settings menu restarts the game the handlers aren't cleared.

**Comment by giann** [comment]
The duplicated keyboard events seem to only happen in the console. So I'll fix the issue by removing it altogether.
