### ISSUE TITLE
Game remains paused after opening a menu

### ISSUE THREAD

**Issue by s-ol** [giann/settlers-issues#5]
When the simulation is running and a menu is opened and then exited via `escape` or by completing an action (e.g. creating a building), I would expect the simulation to resume, however currently the game stays paused.

Similarily it is a bit annoying that the game is paused after an autosave.

**Comment by giann** [comment]
Good point I'll unpause the game when menu are closed.

**Comment by s-ol** [comment]
@giann but don't unpause if the user paused the game by hand before!
