### ISSUE TITLE
Build menu covers cursor

### ISSUE THREAD

**Issue by s-ol** [giann/settlers-issues#7]
Maybe the build menu can move over to the right half of the screen when the cursor starts to overlap it?

**Comment by giann** [comment]
Do you mean you tab-selected something under the menu ?

**Comment by s-ol** [comment]
no, i mean i went to build a house and then wanted to place it in a location that was obscured by the build menu. Solution was to exit the build menu, move the viewport and reopen it, but it would be nice if the whole screen could be used for placing buildings.

**Comment by giann** [comment]
Ok great point. On it.

**Comment by giann** [comment]
In next version 0.0.4a
