### ISSUE TITLE
Crash on pressing key

### ISSUE THREAD

**Issue by QuantumQuacken** [giann/settlers-issues#9]
Sometimes the game crashes when pressing a key like W or P. Completely random. 
Is there a way to see error logs or related?

**Comment by giann** [comment]
You can run the game from a console the stacktrace should be printed out.

**Comment by QuantumQuacken** [comment]
Does the console stacktrace work also in windows cmd? How can I output it? Or i must use Linux? (no problem with it, but I wanted to try it on W).

**Comment by giann** [comment]
No you should not get any output from windows cmd with the game packaged as it is.

**Comment by giann** [comment]
Closing for lack of context
